// src/lib/server/demandAutomation.ts
//
// Motor de automação de Demandas, executado no SERVIDOR (não no navegador).
// Roda periodicamente enquanto o processo Node estiver de pé no VPS — não depende
// de nenhum admin estar logado. Usa o dataService (backend guardião) diretamente,
// sem passar por HTTP.
//
// Os tipos abaixo são um subconjunto deliberadamente duplicado dos tipos definidos
// em src/components/Demandas.tsx (o servidor não importa componentes React). Se os
// campos usados por essa automação mudarem no cliente, replique aqui também.

import * as dataService from "./dataService";

type DemandStatus = "backlog" | "a_fazer" | "em_andamento" | "aguardando" | "revisao" | "concluido";
type DemandPriority = "baixa" | "media" | "alta" | "urgente";
type RecurrenceInterval = "diaria" | "semanal" | "quinzenal" | "mensal";

interface DemandChecklistItem { id: string; text: string; done: boolean; }
interface DemandComment { id: string; author: string; text: string; createdAt: string; }
interface DemandRecurrence {
  interval: RecurrenceInterval;
  active: boolean;
  nextRunDate: string;
  targetStatus: DemandStatus;
}
interface Demand {
  id: string;
  title: string;
  description: string;
  status: DemandStatus;
  priority: DemandPriority;
  clientId?: string;
  projectId?: string;
  assigneeUserId?: string;
  dueDate?: string;
  labels: string[];
  checklist: DemandChecklistItem[];
  comments: DemandComment[];
  createdAt: string;
  updatedAt?: string;
  archived?: boolean;
  autoGenerated?: boolean;
  autoGeneratedKey?: string;
  isRecurringMaster?: boolean;
  recurrence?: DemandRecurrence;
  spawnedFromMasterId?: string;
}
interface DemandTemplate {
  id: string;
  name: string;
  description: string;
  defaultPriority: DemandPriority;
  defaultLabels: string[];
  checklist: string[];
  isDefaultForNewClient?: boolean;
  isDefaultForNewProject?: boolean;
}
interface DemandAutomationSettings {
  id: string;
  quotationsEnabled: boolean;
  quotationPendingDays: number;
  phasesEnabled: boolean;
  phaseDelayDays: number;
  transactionsEnabled: boolean;
  transactionOverdueDays: number;
}
interface Client { id: string; name: string; }
interface Project { id: string; name: string; clientId: string; }
interface Transaction { id: string; projectId: string; description: string; value: number; date: string; status: string; }
interface QuotationRef { id: string; number: number; title: string; date: string; status: string; projectId: string; }
interface PhaseRef { id: string; name: string; startDate: string; endDate: string; progress: number; projectId: string; }

const DEFAULT_SETTINGS: DemandAutomationSettings = {
  id: "default",
  quotationsEnabled: true,
  quotationPendingDays: 5,
  phasesEnabled: true,
  phaseDelayDays: 3,
  transactionsEnabled: true,
  transactionOverdueDays: 3,
};

const todayStr = () => new Date().toISOString().split("T")[0];

const diffDaysFromToday = (dateStr: string): number => {
  const today = new Date(todayStr() + "T00:00:00");
  const target = new Date(dateStr + "T00:00:00");
  return Math.floor((today.getTime() - target.getTime()) / 86400000);
};

const advanceDate = (dateStr: string, interval: RecurrenceInterval): string => {
  const d = new Date(dateStr + "T00:00:00");
  switch (interval) {
    case "diaria": d.setDate(d.getDate() + 1); break;
    case "semanal": d.setDate(d.getDate() + 7); break;
    case "quinzenal": d.setDate(d.getDate() + 14); break;
    case "mensal": d.setMonth(d.getMonth() + 1); break;
  }
  return d.toISOString().split("T")[0];
};

const formatDateBr = (dateStr?: string) => {
  if (!dateStr) return "";
  const parts = dateStr.split("-");
  if (parts.length !== 3) return dateStr;
  return `${parts[2]}/${parts[1]}/${parts[0]}`;
};

type AutoDemandInput = {
  title: string;
  description?: string;
  status?: DemandStatus;
  priority?: DemandPriority;
  clientId?: string;
  projectId?: string;
  assigneeUserId?: string;
  dueDate?: string;
  labels?: string[];
  checklist?: string[];
};

let isRunning = false;

/** Executa um ciclo completo de verificação/automação. Nunca lança — erros são logados. */
export async function runDemandAutomationCycle(): Promise<void> {
  if (isRunning) {
    console.log("[demandAutomation] Ciclo anterior ainda em execução, pulando esta rodada.");
    return;
  }
  isRunning = true;
  try {
    const [demands, templates, settingsList, clients, projects, transactions, quotations, phases] =
      await Promise.all([
        dataService.listCollection("demands") as Promise<Demand[]>,
        dataService.listCollection("demand_templates") as Promise<DemandTemplate[]>,
        dataService.listCollection("demand_settings") as Promise<DemandAutomationSettings[]>,
        dataService.listCollection("clients") as Promise<Client[]>,
        dataService.listCollection("projects") as Promise<Project[]>,
        dataService.listCollection("transactions") as Promise<Transaction[]>,
        dataService.listCollection("quotation_maps") as Promise<QuotationRef[]>,
        dataService.listCollection("timeline_phases") as Promise<PhaseRef[]>,
      ]);

    const settings = settingsList.find((s) => s.id === "default") || DEFAULT_SETTINGS;
    const today = todayStr();

    const activeDemands = demands.filter((d) => !d.archived);
    const byKey = new Map<string, Demand>();
    activeDemands.forEach((d) => { if (d.autoGeneratedKey) byKey.set(d.autoGeneratedKey, d); });

    let created = 0;
    let resolved = 0;

    const createAuto = async (key: string, input: AutoDemandInput) => {
      if (byKey.has(key)) return;
      const newDemand: Demand = {
        id: `demand-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
        title: input.title,
        description: input.description || "",
        status: input.status || "backlog",
        priority: input.priority || "media",
        clientId: input.clientId,
        projectId: input.projectId,
        assigneeUserId: input.assigneeUserId,
        dueDate: input.dueDate,
        labels: input.labels && input.labels.length > 0 ? input.labels : ["automático"],
        checklist: (input.checklist || []).map((text, i) => ({ id: `chk-${Date.now()}-${i}`, text, done: false })),
        comments: [],
        createdAt: new Date().toISOString(),
        autoGenerated: true,
        autoGeneratedKey: key,
      };
      byKey.set(key, newDemand); // evita duplicar dentro do mesmo ciclo
      await dataService.setDocById("demands", newDemand.id, newDemand);
      created++;
    };

    const resolveAuto = async (key: string) => {
      const d = byKey.get(key);
      if (!d || d.status === "concluido") return;
      const updated = { ...d, status: "concluido" as DemandStatus, updatedAt: new Date().toISOString() };
      byKey.set(key, updated);
      await dataService.setDocById("demands", d.id, updated);
      resolved++;
    };

    // 1) Onboarding — cliente novo
    const clientTemplate = templates.find((t) => t.isDefaultForNewClient);
    if (clientTemplate) {
      for (const c of clients) {
        const key = `onboarding-client:${c.id}`;
        if (!byKey.has(key)) {
          await createAuto(key, {
            title: `Onboarding — ${c.name}`,
            description: "Checklist de boas-vindas gerado automaticamente para o novo cliente.",
            status: "a_fazer",
            priority: clientTemplate.defaultPriority,
            clientId: c.id,
            labels: [...clientTemplate.defaultLabels, "automático"],
            checklist: clientTemplate.checklist,
          });
        }
      }
    }

    // 2) Onboarding — obra/projeto novo
    const projectTemplate = templates.find((t) => t.isDefaultForNewProject);
    if (projectTemplate) {
      for (const p of projects) {
        const key = `onboarding-project:${p.id}`;
        if (!byKey.has(key)) {
          await createAuto(key, {
            title: `Kickoff — ${p.name}`,
            description: "Checklist de início de obra/projeto gerado automaticamente.",
            status: "a_fazer",
            priority: projectTemplate.defaultPriority,
            clientId: p.clientId,
            projectId: p.id,
            labels: [...projectTemplate.defaultLabels, "automático"],
            checklist: projectTemplate.checklist,
          });
        }
      }
    }

    // 3) Cotações paradas em "pendente"
    if (settings.quotationsEnabled) {
      for (const q of quotations) {
        const key = `quotation:${q.id}`;
        if (q.status === "pendente") {
          const days = diffDaysFromToday(q.date);
          if (days >= settings.quotationPendingDays) {
            const project = projects.find((p) => p.id === q.projectId);
            await createAuto(key, {
              title: `Cotação #${q.number} parada há ${days} dia(s)`,
              description: `"${q.title}" está pendente sem movimentação. Verifique o retorno dos fornecedores.`,
              status: "a_fazer",
              priority: days >= settings.quotationPendingDays * 2 ? "urgente" : "alta",
              projectId: q.projectId,
              clientId: project?.clientId,
              labels: ["financeiro", "automático"],
              checklist: ["Cobrar retorno dos fornecedores", "Revisar prazos de entrega", "Atualizar status da cotação"],
            });
          }
        } else {
          await resolveAuto(key);
        }
      }
    }

    // 4) Fases de cronograma físico atrasadas
    if (settings.phasesEnabled) {
      for (const ph of phases) {
        const key = `phase:${ph.id}`;
        const progress = typeof ph.progress === "number" ? ph.progress : 0;
        const isLate = !!ph.endDate && ph.endDate < today && progress < 100;
        if (isLate) {
          const days = diffDaysFromToday(ph.endDate);
          if (days >= settings.phaseDelayDays) {
            const project = projects.find((p) => p.id === ph.projectId);
            await createAuto(key, {
              title: `Fase "${ph.name}" atrasada há ${days} dia(s)`,
              description: `Etapa do cronograma físico ultrapassou o prazo previsto (${formatDateBr(ph.endDate)}) com ${progress}% concluído.`,
              status: "a_fazer",
              priority: days >= settings.phaseDelayDays * 3 ? "urgente" : "alta",
              projectId: ph.projectId,
              clientId: project?.clientId,
              labels: ["obra", "automático"],
              checklist: ["Atualizar avanço físico", "Registrar motivo do atraso", "Ajustar cronograma se necessário"],
            });
          }
        } else {
          await resolveAuto(key);
        }
      }
    }

    // 5) Transações financeiras pendentes vencidas
    if (settings.transactionsEnabled) {
      for (const tx of transactions) {
        const key = `transaction:${tx.id}`;
        if (tx.status === "pendente") {
          const days = diffDaysFromToday(tx.date);
          if (days >= settings.transactionOverdueDays) {
            const project = projects.find((p) => p.id === tx.projectId);
            await createAuto(key, {
              title: `Cobrança pendente: ${tx.description}`,
              description: `Lançamento financeiro pendente há ${days} dia(s), no valor de R$ ${tx.value.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}.`,
              status: "a_fazer",
              priority: days >= settings.transactionOverdueDays * 3 ? "urgente" : "alta",
              projectId: tx.projectId,
              clientId: project?.clientId,
              labels: ["financeiro", "automático"],
              checklist: ["Entrar em contato para cobrança", "Confirmar comprovante de pagamento"],
            });
          }
        } else {
          await resolveAuto(key);
        }
      }
    }

    // 6) Recorrências — gera a próxima instância quando a data chega
    const masters = demands.filter((d) => d.isRecurringMaster && d.recurrence?.active);
    for (const master of masters) {
      const rec = master.recurrence!;
      if (rec.nextRunDate <= today) {
        const instanceKey = `recurrence:${master.id}:${rec.nextRunDate}`;
        if (!byKey.has(instanceKey)) {
          await createAuto(instanceKey, {
            title: master.title,
            description: master.description,
            status: rec.targetStatus,
            priority: master.priority,
            clientId: master.clientId,
            projectId: master.projectId,
            assigneeUserId: master.assigneeUserId,
            dueDate: rec.nextRunDate,
            labels: master.labels,
            checklist: master.checklist.map((i) => i.text),
          });
        }
        const nextRunDate = advanceDate(rec.nextRunDate, rec.interval);
        await dataService.setDocById("demands", master.id, {
          ...master,
          recurrence: { ...rec, nextRunDate },
          updatedAt: new Date().toISOString(),
        });
      }
    }

    if (created > 0 || resolved > 0) {
      console.log(`[demandAutomation] Ciclo concluído: ${created} demanda(s) criada(s), ${resolved} resolvida(s).`);
    }
  } catch (err: any) {
    console.error("[demandAutomation] Falha no ciclo de automação:", err?.message || err);
  } finally {
    isRunning = false;
  }
}

/**
 * Inicia o agendamento recorrente do motor de automação. Roda uma vez imediatamente
 * (com um pequeno atraso para não competir com o boot do servidor) e depois a cada
 * `intervalMinutes` minutos, para sempre, enquanto o processo estiver de pé.
 */
export function startDemandAutomationScheduler(intervalMinutes = 10): void {
  const intervalMs = Math.max(1, intervalMinutes) * 60 * 1000;
  setTimeout(() => { void runDemandAutomationCycle(); }, 15_000);
  setInterval(() => { void runDemandAutomationCycle(); }, intervalMs);
  console.log(`[demandAutomation] Agendador iniciado (a cada ${intervalMinutes} min).`);
}
