import React, { useState, useEffect, useMemo } from 'react';
import { Client, Project, User } from '../types';
import {
  Plus,
  Trash2,
  Edit,
  Search,
  Filter,
  X,
  ChevronLeft,
  ChevronRight,
  Flag,
  CheckSquare,
  Square,
  MessageSquare,
  Calendar,
  User as UserIcon,
  Tag as TagIcon,
  Building,
  Briefcase,
  AlertTriangle,
  Archive,
  GripVertical,
  Send,
  Layers,
  Kanban,
  Repeat,
  Settings,
  Zap,
  Pause,
  Play,
  Sparkles
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { subscribeCollection, saveDoc, removeDoc } from '../lib/firebaseDb';

// ============================================================
// TIPOS — Demandas (CRM interno estilo kanban)
// ============================================================

export type DemandStatus = 'backlog' | 'a_fazer' | 'em_andamento' | 'aguardando' | 'revisao' | 'concluido';
export type DemandPriority = 'baixa' | 'media' | 'alta' | 'urgente';
export type RecurrenceInterval = 'diaria' | 'semanal' | 'quinzenal' | 'mensal';

export interface DemandChecklistItem {
  id: string;
  text: string;
  done: boolean;
}

export interface DemandComment {
  id: string;
  author: string;
  text: string;
  createdAt: string; // ISO
}

export interface DemandRecurrence {
  interval: RecurrenceInterval;
  active: boolean;
  nextRunDate: string; // YYYY-MM-DD
  targetStatus: DemandStatus; // coluna onde a instância nasce
}

export interface Demand {
  id: string;
  title: string;
  description: string;
  status: DemandStatus;
  priority: DemandPriority;
  clientId?: string;
  projectId?: string;
  assigneeUserId?: string;
  dueDate?: string; // YYYY-MM-DD
  labels: string[];
  checklist: DemandChecklistItem[];
  comments: DemandComment[];
  createdAt: string; // ISO
  updatedAt?: string; // ISO
  archived?: boolean;
  // Automação
  autoGenerated?: boolean;
  autoGeneratedKey?: string; // chave de dedupe, ex: 'quotation:abc123'
  // Recorrência — quando isRecurringMaster=true este documento é um "molde" e não aparece no quadro
  isRecurringMaster?: boolean;
  recurrence?: DemandRecurrence;
  spawnedFromMasterId?: string;
}

export interface DemandTemplate {
  id: string;
  name: string;
  description: string;
  defaultPriority: DemandPriority;
  defaultLabels: string[];
  checklist: string[]; // textos dos itens
  isDefaultForNewClient?: boolean;
  isDefaultForNewProject?: boolean;
  createdAt: string;
}

export interface DemandAutomationSettings {
  id: string; // 'default'
  quotationsEnabled: boolean;
  quotationPendingDays: number;
  phasesEnabled: boolean;
  phaseDelayDays: number;
  transactionsEnabled: boolean;
  transactionOverdueDays: number;
}

const DEFAULT_SETTINGS: DemandAutomationSettings = {
  id: 'default',
  quotationsEnabled: true,
  quotationPendingDays: 5,
  phasesEnabled: true,
  phaseDelayDays: 3,
  transactionsEnabled: true,
  transactionOverdueDays: 3,
};

const STATUS_COLUMNS: { id: DemandStatus; label: string; headerColor: string }[] = [
  { id: 'backlog', label: 'Backlog', headerColor: 'border-t-stone-400 bg-stone-50' },
  { id: 'a_fazer', label: 'A Fazer', headerColor: 'border-t-slate-400 bg-slate-50' },
  { id: 'em_andamento', label: 'Em Andamento', headerColor: 'border-t-blue-400 bg-blue-50/30' },
  { id: 'aguardando', label: 'Aguardando', headerColor: 'border-t-amber-400 bg-amber-50/30' },
  { id: 'revisao', label: 'Revisão', headerColor: 'border-t-purple-400 bg-purple-50/30' },
  { id: 'concluido', label: 'Concluído', headerColor: 'border-t-emerald-400 bg-emerald-50/30' },
];

const PRIORITY_CONFIG: Record<DemandPriority, { label: string; badge: string; border: string }> = {
  baixa: { label: 'Baixa', badge: 'bg-stone-100 text-stone-600 border-stone-200', border: 'border-l-stone-300' },
  media: { label: 'Média', badge: 'bg-blue-50 text-blue-700 border-blue-100', border: 'border-l-blue-400' },
  alta: { label: 'Alta', badge: 'bg-orange-50 text-orange-700 border-orange-100', border: 'border-l-orange-400' },
  urgente: { label: 'Urgente', badge: 'bg-red-50 text-red-700 border-red-100', border: 'border-l-red-500' },
};

const RECURRENCE_LABELS: Record<RecurrenceInterval, string> = {
  diaria: 'Diária',
  semanal: 'Semanal',
  quinzenal: 'Quinzenal',
  mensal: 'Mensal',
};

// ============================================================
// HELPERS
// ============================================================

const todayStr = () => new Date().toISOString().split('T')[0];

const diffDaysFromToday = (dateStr: string): number => {
  const today = new Date(todayStr() + 'T00:00:00');
  const target = new Date(dateStr + 'T00:00:00');
  return Math.floor((today.getTime() - target.getTime()) / 86400000);
};

const advanceDate = (dateStr: string, interval: RecurrenceInterval): string => {
  const d = new Date(dateStr + 'T00:00:00');
  switch (interval) {
    case 'diaria': d.setDate(d.getDate() + 1); break;
    case 'semanal': d.setDate(d.getDate() + 7); break;
    case 'quinzenal': d.setDate(d.getDate() + 14); break;
    case 'mensal': d.setMonth(d.getMonth() + 1); break;
  }
  return d.toISOString().split('T')[0];
};

const formatDate = (dateStr?: string) => {
  if (!dateStr) return '';
  const parts = dateStr.split('-');
  if (parts.length !== 3) return dateStr;
  return `${parts[2]}/${parts[1]}/${parts[0]}`;
};

// ============================================================
// COMPONENTE PRINCIPAL — Quadro Kanban
// ============================================================

interface DemandasProps {
  clients: Client[];
  projects: Project[];
  users: User[];
}

const emptyForm = () => ({
  title: '',
  description: '',
  status: 'backlog' as DemandStatus,
  priority: 'media' as DemandPriority,
  clientId: '',
  projectId: '',
  assigneeUserId: '',
  dueDate: '',
  labels: '' as string, // comma separated in the form
});

const emptyTemplateForm = () => ({
  name: '',
  description: '',
  defaultPriority: 'media' as DemandPriority,
  defaultLabels: '',
  checklist: '',
  isDefaultForNewClient: false,
  isDefaultForNewProject: false,
});

const emptyRecForm = () => ({
  title: '',
  description: '',
  priority: 'media' as DemandPriority,
  labels: '',
  clientId: '',
  projectId: '',
  assigneeUserId: '',
  interval: 'semanal' as RecurrenceInterval,
  targetStatus: 'a_fazer' as DemandStatus,
  checklist: '',
  startDate: todayStr(),
});

export default function Demandas({ clients, projects, users }: DemandasProps) {
  const [demands, setDemands] = useState<Demand[]>([]);
  const [templates, setTemplates] = useState<DemandTemplate[]>([]);
  const [settingsList, setSettingsList] = useState<DemandAutomationSettings[]>([]);

  const [searchQuery, setSearchQuery] = useState('');
  const [priorityFilter, setPriorityFilter] = useState<'all' | DemandPriority>('all');
  const [clientFilter, setClientFilter] = useState<string>('all');
  const [projectFilter, setProjectFilter] = useState<string>('all');
  const [assigneeFilter, setAssigneeFilter] = useState<string>('all');
  const [showFilters, setShowFilters] = useState(false);
  const [showArchived, setShowArchived] = useState(false);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingDemand, setEditingDemand] = useState<Demand | null>(null);
  const [form, setForm] = useState(emptyForm());
  const [formChecklist, setFormChecklist] = useState<string[]>([]);
  const [applyTemplateId, setApplyTemplateId] = useState('');

  const [detailDemand, setDetailDemand] = useState<Demand | null>(null);
  const [newChecklistText, setNewChecklistText] = useState('');
  const [newCommentText, setNewCommentText] = useState('');
  const [commentAuthor, setCommentAuthor] = useState(() => {
    try { return localStorage.getItem('cbc_demandas_last_author') || ''; } catch { return ''; }
  });

  const [quickAddColumn, setQuickAddColumn] = useState<DemandStatus | null>(null);
  const [quickAddText, setQuickAddText] = useState('');

  const [dragOverColumn, setDragOverColumn] = useState<DemandStatus | null>(null);
  const [draggingId, setDraggingId] = useState<string | null>(null);

  // Modelos
  const [isTemplatesOpen, setIsTemplatesOpen] = useState(false);
  const [editingTemplate, setEditingTemplate] = useState<DemandTemplate | null>(null);
  const [templateForm, setTemplateForm] = useState(emptyTemplateForm());

  // Recorrências
  const [isRecurrenceOpen, setIsRecurrenceOpen] = useState(false);
  const [editingRecurrence, setEditingRecurrence] = useState<Demand | null>(null);
  const [recForm, setRecForm] = useState(emptyRecForm());

  // Automação
  const [isAutomationOpen, setIsAutomationOpen] = useState(false);
  const [autoForm, setAutoForm] = useState<DemandAutomationSettings>(DEFAULT_SETTINGS);

  useEffect(() => {
    const u1 = subscribeCollection('demands', setDemands, [], 'cbc_demands');
    const u2 = subscribeCollection('demand_templates', setTemplates, [], 'cbc_demand_templates');
    const u3 = subscribeCollection('demand_settings', setSettingsList, [], 'cbc_demand_settings');
    return () => { u1(); u2(); u3(); };
  }, []);

  // Mantém o modal de detalhe sincronizado com os dados atualizados do polling
  useEffect(() => {
    if (detailDemand) {
      const fresh = demands.find(d => d.id === detailDemand.id);
      if (fresh) setDetailDemand(fresh);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [demands]);

  const teamMembers = useMemo(
    () => users.filter(u => u.role === 'admin' || u.role === 'marketing'),
    [users]
  );

  const getUserName = (id?: string) => (id ? users.find(u => u.id === id)?.name : undefined);

  const currentAutomationSettings: DemandAutomationSettings =
    settingsList.find(s => s.id === 'default') || DEFAULT_SETTINGS;

  const recurringMasters = useMemo(() => demands.filter(d => d.isRecurringMaster), [demands]);

  const isOverdue = (d: Demand) => {
    if (!d.dueDate || d.status === 'concluido') return false;
    return d.dueDate < todayStr();
  };

  // O quadro nunca exibe os "moldes" de recorrência — só as instâncias reais de trabalho.
  const boardDemands = useMemo(() => demands.filter(d => !d.isRecurringMaster), [demands]);

  const filteredDemands = useMemo(() => {
    const q = searchQuery.trim().toLowerCase();
    return boardDemands
      .filter(d => (showArchived ? true : !d.archived))
      .filter(d => {
        if (q && !d.title.toLowerCase().includes(q) && !d.description.toLowerCase().includes(q)) return false;
        if (priorityFilter !== 'all' && d.priority !== priorityFilter) return false;
        if (clientFilter !== 'all' && d.clientId !== clientFilter) return false;
        if (projectFilter !== 'all' && d.projectId !== projectFilter) return false;
        if (assigneeFilter !== 'all' && d.assigneeUserId !== assigneeFilter) return false;
        return true;
      });
  }, [boardDemands, searchQuery, priorityFilter, clientFilter, projectFilter, assigneeFilter, showArchived]);

  const projectsForClient = (clientId: string) => projects.filter(p => p.clientId === clientId);

  const getClientName = (id?: string) => clients.find(c => c.id === id)?.name;
  const getProjectName = (id?: string) => projects.find(p => p.id === id)?.name;

  const stats = useMemo(() => {
    const active = boardDemands.filter(d => !d.archived);
    const overdue = active.filter(isOverdue).length;
    const emAndamento = active.filter(d => d.status === 'em_andamento').length;
    const weekAgo = new Date();
    weekAgo.setDate(weekAgo.getDate() - 7);
    const concluidasSemana = active.filter(d => {
      if (d.status !== 'concluido' || !d.updatedAt) return false;
      return new Date(d.updatedAt) >= weekAgo;
    }).length;
    const automaticas = active.filter(d => d.autoGenerated && d.status !== 'concluido').length;
    return { total: active.length, overdue, emAndamento, concluidasSemana, automaticas };
  }, [boardDemands]);

  // ---------- CRUD de demandas ----------

  const resetForm = () => { setForm(emptyForm()); setFormChecklist([]); setApplyTemplateId(''); };

  const handleOpenCreate = (defaultStatus?: DemandStatus) => {
    setEditingDemand(null);
    resetForm();
    if (defaultStatus) setForm(f => ({ ...f, status: defaultStatus }));
    setIsModalOpen(true);
  };

  const handleOpenEdit = (d: Demand) => {
    setEditingDemand(d);
    setForm({
      title: d.title,
      description: d.description,
      status: d.status,
      priority: d.priority,
      clientId: d.clientId || '',
      projectId: d.projectId || '',
      assigneeUserId: d.assigneeUserId || '',
      dueDate: d.dueDate || '',
      labels: (d.labels || []).join(', '),
    });
    setFormChecklist([]);
    setApplyTemplateId('');
    setIsModalOpen(true);
  };

  const handleApplyTemplateToForm = () => {
    const t = templates.find(x => x.id === applyTemplateId);
    if (!t) return;
    setForm(f => {
      const currentLabels = f.labels ? f.labels.split(',').map(s => s.trim()).filter(Boolean) : [];
      const mergedLabels = Array.from(new Set([...currentLabels, ...t.defaultLabels]));
      return {
        ...f,
        description: f.description || t.description,
        priority: t.defaultPriority,
        labels: mergedLabels.join(', '),
      };
    });
    if (!editingDemand) {
      setFormChecklist(prev => Array.from(new Set([...prev, ...t.checklist])));
    }
  };

  const handleSaveDemand = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.title.trim()) {
      alert('Informe um título para a demanda.');
      return;
    }

    const labelsArr = form.labels.split(',').map(l => l.trim()).filter(Boolean);

    try {
      if (editingDemand) {
        const updated: Demand = {
          ...editingDemand,
          title: form.title.trim(),
          description: form.description.trim(),
          status: form.status,
          priority: form.priority,
          clientId: form.clientId || undefined,
          projectId: form.projectId || undefined,
          assigneeUserId: form.assigneeUserId || undefined,
          dueDate: form.dueDate || undefined,
          labels: labelsArr,
          updatedAt: new Date().toISOString(),
        };
        await saveDoc('demands', updated.id, updated);
      } else {
        const newDemand: Demand = {
          id: `demand-${Date.now()}`,
          title: form.title.trim(),
          description: form.description.trim(),
          status: form.status,
          priority: form.priority,
          clientId: form.clientId || undefined,
          projectId: form.projectId || undefined,
          assigneeUserId: form.assigneeUserId || undefined,
          dueDate: form.dueDate || undefined,
          labels: labelsArr,
          checklist: formChecklist.map((text, i) => ({ id: `chk-${Date.now()}-${i}`, text, done: false })),
          comments: [],
          createdAt: new Date().toISOString(),
        };
        await saveDoc('demands', newDemand.id, newDemand);
      }
      setIsModalOpen(false);
      resetForm();
      setEditingDemand(null);
    } catch (err: any) {
      alert('Falha ao salvar demanda: ' + (err.message || err));
    }
  };

  const handleDeleteDemand = async (id: string) => {
    if (!confirm('Excluir esta demanda permanentemente? Esta ação não pode ser desfeita.')) return;
    try {
      await removeDoc('demands', id);
      if (detailDemand?.id === id) setDetailDemand(null);
    } catch (err: any) {
      alert('Falha ao excluir demanda: ' + (err.message || err));
    }
  };

  const handleArchive = async (d: Demand, archived: boolean) => {
    await saveDoc('demands', d.id, { ...d, archived, updatedAt: new Date().toISOString() });
  };

  const handleMoveStatus = async (d: Demand, direction: 'left' | 'right') => {
    const idx = STATUS_COLUMNS.findIndex(c => c.id === d.status);
    const newIdx = direction === 'left' ? idx - 1 : idx + 1;
    if (newIdx < 0 || newIdx >= STATUS_COLUMNS.length) return;
    const newStatus = STATUS_COLUMNS[newIdx].id;
    await saveDoc('demands', d.id, { ...d, status: newStatus, updatedAt: new Date().toISOString() });
  };

  const handleDropOnColumn = async (colStatus: DemandStatus) => {
    setDragOverColumn(null);
    if (!draggingId) return;
    const d = demands.find(x => x.id === draggingId);
    setDraggingId(null);
    if (!d || d.status === colStatus) return;
    await saveDoc('demands', d.id, { ...d, status: colStatus, updatedAt: new Date().toISOString() });
  };

  const handleQuickAdd = async (colStatus: DemandStatus) => {
    if (!quickAddText.trim()) { setQuickAddColumn(null); return; }
    const newDemand: Demand = {
      id: `demand-${Date.now()}`,
      title: quickAddText.trim(),
      description: '',
      status: colStatus,
      priority: 'media',
      labels: [],
      checklist: [],
      comments: [],
      createdAt: new Date().toISOString(),
    };
    try {
      await saveDoc('demands', newDemand.id, newDemand);
      setQuickAddText('');
      setQuickAddColumn(colStatus);
    } catch (err: any) {
      alert('Falha ao criar demanda: ' + (err.message || err));
    }
  };

  // ---------- Checklist & Comentários (modal de detalhe) ----------

  const handleAddChecklistItem = async () => {
    if (!detailDemand || !newChecklistText.trim()) return;
    const item: DemandChecklistItem = { id: `chk-${Date.now()}`, text: newChecklistText.trim(), done: false };
    const updated: Demand = { ...detailDemand, checklist: [...detailDemand.checklist, item], updatedAt: new Date().toISOString() };
    setDetailDemand(updated);
    setNewChecklistText('');
    await saveDoc('demands', updated.id, updated);
  };

  const handleToggleChecklistItem = async (itemId: string) => {
    if (!detailDemand) return;
    const updated: Demand = {
      ...detailDemand,
      checklist: detailDemand.checklist.map(i => i.id === itemId ? { ...i, done: !i.done } : i),
      updatedAt: new Date().toISOString(),
    };
    setDetailDemand(updated);
    await saveDoc('demands', updated.id, updated);
  };

  const handleRemoveChecklistItem = async (itemId: string) => {
    if (!detailDemand) return;
    const updated: Demand = {
      ...detailDemand,
      checklist: detailDemand.checklist.filter(i => i.id !== itemId),
      updatedAt: new Date().toISOString(),
    };
    setDetailDemand(updated);
    await saveDoc('demands', updated.id, updated);
  };

  const handleApplyTemplateToDetail = async (templateId: string) => {
    if (!detailDemand || !templateId) return;
    const t = templates.find(x => x.id === templateId);
    if (!t) return;
    const existingTexts = new Set(detailDemand.checklist.map(i => i.text));
    const newItems = t.checklist
      .filter(text => !existingTexts.has(text))
      .map((text, i) => ({ id: `chk-${Date.now()}-${i}`, text, done: false }));
    const updated: Demand = { ...detailDemand, checklist: [...detailDemand.checklist, ...newItems], updatedAt: new Date().toISOString() };
    setDetailDemand(updated);
    await saveDoc('demands', updated.id, updated);
  };

  const handleAddComment = async () => {
    if (!detailDemand || !newCommentText.trim()) return;
    const author = commentAuthor.trim() || 'Equipe';
    try { localStorage.setItem('cbc_demandas_last_author', author); } catch { /* ignore */ }
    const comment: DemandComment = { id: `cmt-${Date.now()}`, author, text: newCommentText.trim(), createdAt: new Date().toISOString() };
    const updated: Demand = { ...detailDemand, comments: [...detailDemand.comments, comment], updatedAt: new Date().toISOString() };
    setDetailDemand(updated);
    setNewCommentText('');
    await saveDoc('demands', updated.id, updated);
  };

  // ---------- Modelos ----------

  const handleOpenNewTemplate = () => { setEditingTemplate(null); setTemplateForm(emptyTemplateForm()); };

  const handleEditTemplateClick = (t: DemandTemplate) => {
    setEditingTemplate(t);
    setTemplateForm({
      name: t.name,
      description: t.description || '',
      defaultPriority: t.defaultPriority,
      defaultLabels: t.defaultLabels.join(', '),
      checklist: t.checklist.join('\n'),
      isDefaultForNewClient: !!t.isDefaultForNewClient,
      isDefaultForNewProject: !!t.isDefaultForNewProject,
    });
  };

  const handleSaveTemplate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!templateForm.name.trim()) { alert('Informe um nome para o modelo.'); return; }

    const checklistArr = templateForm.checklist.split('\n').map(s => s.trim()).filter(Boolean);
    const labelsArr = templateForm.defaultLabels.split(',').map(s => s.trim()).filter(Boolean);
    const id = editingTemplate ? editingTemplate.id : `tmpl-${Date.now()}`;

    const tmpl: DemandTemplate = {
      id,
      name: templateForm.name.trim(),
      description: templateForm.description.trim(),
      defaultPriority: templateForm.defaultPriority,
      defaultLabels: labelsArr,
      checklist: checklistArr,
      isDefaultForNewClient: templateForm.isDefaultForNewClient,
      isDefaultForNewProject: templateForm.isDefaultForNewProject,
      createdAt: editingTemplate?.createdAt || new Date().toISOString(),
    };

    try {
      // Garante que só exista um modelo padrão de cada tipo por vez.
      if (tmpl.isDefaultForNewClient) {
        for (const t of templates) {
          if (t.id !== id && t.isDefaultForNewClient) await saveDoc('demand_templates', t.id, { ...t, isDefaultForNewClient: false });
        }
      }
      if (tmpl.isDefaultForNewProject) {
        for (const t of templates) {
          if (t.id !== id && t.isDefaultForNewProject) await saveDoc('demand_templates', t.id, { ...t, isDefaultForNewProject: false });
        }
      }
      await saveDoc('demand_templates', id, tmpl);
      setEditingTemplate(null);
      setTemplateForm(emptyTemplateForm());
    } catch (err: any) {
      alert('Falha ao salvar modelo: ' + (err.message || err));
    }
  };

  const handleDeleteTemplate = async (id: string) => {
    if (!confirm('Excluir este modelo? Demandas já criadas a partir dele não são afetadas.')) return;
    try {
      await removeDoc('demand_templates', id);
      if (editingTemplate?.id === id) { setEditingTemplate(null); setTemplateForm(emptyTemplateForm()); }
    } catch (err: any) {
      alert('Falha ao excluir modelo: ' + (err.message || err));
    }
  };

  // ---------- Recorrências ----------

  const handleOpenNewRecurrence = () => { setEditingRecurrence(null); setRecForm(emptyRecForm()); };

  const handleEditRecurrenceClick = (m: Demand) => {
    setEditingRecurrence(m);
    setRecForm({
      title: m.title,
      description: m.description,
      priority: m.priority,
      labels: m.labels.join(', '),
      clientId: m.clientId || '',
      projectId: m.projectId || '',
      assigneeUserId: m.assigneeUserId || '',
      interval: m.recurrence?.interval || 'semanal',
      targetStatus: m.recurrence?.targetStatus || 'a_fazer',
      checklist: m.checklist.map(c => c.text).join('\n'),
      startDate: m.recurrence?.nextRunDate || todayStr(),
    });
  };

  const handleSaveRecurrence = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!recForm.title.trim()) { alert('Informe um título.'); return; }

    const checklistArr = recForm.checklist.split('\n').map(s => s.trim()).filter(Boolean);
    const labelsArr = recForm.labels.split(',').map(s => s.trim()).filter(Boolean);
    const id = editingRecurrence ? editingRecurrence.id : `demand-rec-${Date.now()}`;

    const master: Demand = {
      id,
      title: recForm.title.trim(),
      description: recForm.description.trim(),
      status: 'backlog',
      priority: recForm.priority,
      clientId: recForm.clientId || undefined,
      projectId: recForm.projectId || undefined,
      assigneeUserId: recForm.assigneeUserId || undefined,
      labels: labelsArr,
      checklist: checklistArr.map((text, i) => ({ id: `chk-${Date.now()}-${i}`, text, done: false })),
      comments: editingRecurrence?.comments || [],
      createdAt: editingRecurrence?.createdAt || new Date().toISOString(),
      isRecurringMaster: true,
      recurrence: {
        interval: recForm.interval,
        active: editingRecurrence?.recurrence?.active ?? true,
        nextRunDate: recForm.startDate || todayStr(),
        targetStatus: recForm.targetStatus,
      },
    };

    try {
      await saveDoc('demands', id, master);
      setEditingRecurrence(null);
      setRecForm(emptyRecForm());
    } catch (err: any) {
      alert('Falha ao salvar recorrência: ' + (err.message || err));
    }
  };

  const handleToggleRecurrenceActive = async (m: Demand) => {
    if (!m.recurrence) return;
    try {
      await saveDoc('demands', m.id, { ...m, recurrence: { ...m.recurrence, active: !m.recurrence.active } });
    } catch (err: any) {
      alert('Falha ao atualizar recorrência: ' + (err.message || err));
    }
  };

  const handleDeleteRecurrence = async (id: string) => {
    if (!confirm('Excluir esta recorrência? As demandas já geradas por ela permanecem no quadro.')) return;
    try {
      await removeDoc('demands', id);
      if (editingRecurrence?.id === id) { setEditingRecurrence(null); setRecForm(emptyRecForm()); }
    } catch (err: any) {
      alert('Falha ao excluir recorrência: ' + (err.message || err));
    }
  };

  // ---------- Configurações de automação ----------

  const handleOpenAutomation = () => { setAutoForm(currentAutomationSettings); setIsAutomationOpen(true); };

  const handleSaveAutomation = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await saveDoc('demand_settings', 'default', { ...autoForm, id: 'default' });
      setIsAutomationOpen(false);
    } catch (err: any) {
      alert('Falha ao salvar configurações: ' + (err.message || err));
    }
  };

  const clearFilters = () => {
    setSearchQuery('');
    setPriorityFilter('all');
    setClientFilter('all');
    setProjectFilter('all');
    setAssigneeFilter('all');
  };

  const hasActiveFilters = priorityFilter !== 'all' || clientFilter !== 'all' || projectFilter !== 'all' || assigneeFilter !== 'all' || searchQuery.trim() !== '';

  // ---------- Render ----------

  return (
    <div className="space-y-5 font-sans">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
        <div className="space-y-0.5">
          <h3 className="font-serif text-xl text-stone-900 font-bold flex items-center gap-2">
            <Kanban size={18} className="text-[#FF5A35]" /> Demandas
          </h3>
          <p className="text-[10px] text-stone-400 italic font-mono">
            CRM interno em quadro kanban, com automações exclusivas integradas ao restante do sistema.
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handleOpenAutomation}
            className="flex items-center gap-1.5 px-3 py-2.5 border border-stone-200 bg-white text-stone-600 hover:bg-stone-50 font-mono text-[10px] uppercase tracking-wider font-bold cursor-pointer"
            title="Configurar automações"
          >
            <Settings size={13} /> Automação
          </button>
          <button
            onClick={() => { handleOpenNewRecurrence(); setIsRecurrenceOpen(true); }}
            className="flex items-center gap-1.5 px-3 py-2.5 border border-stone-200 bg-white text-stone-600 hover:bg-stone-50 font-mono text-[10px] uppercase tracking-wider font-bold cursor-pointer"
            title="Gerenciar demandas recorrentes"
          >
            <Repeat size={13} /> Recorrências {recurringMasters.length > 0 && `(${recurringMasters.length})`}
          </button>
          <button
            onClick={() => { handleOpenNewTemplate(); setIsTemplatesOpen(true); }}
            className="flex items-center gap-1.5 px-3 py-2.5 border border-stone-200 bg-white text-stone-600 hover:bg-stone-50 font-mono text-[10px] uppercase tracking-wider font-bold cursor-pointer"
            title="Gerenciar modelos"
          >
            <Layers size={13} /> Modelos {templates.length > 0 && `(${templates.length})`}
          </button>
          <button
            onClick={() => handleOpenCreate()}
            className="bg-stone-900 hover:bg-stone-800 text-white font-mono text-[10px] uppercase tracking-wider font-bold py-2.5 px-4 flex items-center gap-1.5 border border-stone-800 transition-all cursor-pointer"
          >
            <Plus size={14} /> Nova Demanda
          </button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
        <div className="border border-stone-200 bg-white p-3.5 space-y-1">
          <p className="text-[9px] font-mono uppercase tracking-wider text-stone-400 font-bold">Total Ativo</p>
          <p className="text-xl font-serif font-bold text-stone-900">{stats.total}</p>
        </div>
        <div className="border border-stone-200 bg-white p-3.5 space-y-1">
          <p className="text-[9px] font-mono uppercase tracking-wider text-stone-400 font-bold">Em Andamento</p>
          <p className="text-xl font-serif font-bold text-blue-600">{stats.emAndamento}</p>
        </div>
        <div className="border border-stone-200 bg-white p-3.5 space-y-1">
          <p className="text-[9px] font-mono uppercase tracking-wider text-stone-400 font-bold flex items-center gap-1">
            <AlertTriangle size={10} /> Atrasadas
          </p>
          <p className="text-xl font-serif font-bold text-red-600">{stats.overdue}</p>
        </div>
        <div className="border border-stone-200 bg-white p-3.5 space-y-1">
          <p className="text-[9px] font-mono uppercase tracking-wider text-stone-400 font-bold">Concluídas (7d)</p>
          <p className="text-xl font-serif font-bold text-emerald-600">{stats.concluidasSemana}</p>
        </div>
        <div className="border border-stone-200 bg-white p-3.5 space-y-1">
          <p className="text-[9px] font-mono uppercase tracking-wider text-stone-400 font-bold flex items-center gap-1">
            <Zap size={10} /> Geradas pelo Sistema
          </p>
          <p className="text-xl font-serif font-bold text-purple-600">{stats.automaticas}</p>
        </div>
      </div>

      {/* Search & filters */}
      <div className="space-y-2">
        <div className="flex flex-col md:flex-row gap-2">
          <div className="relative flex-grow">
            <Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-400" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Buscar por título ou descrição..."
              className="w-full bg-white border border-stone-200 pl-8 pr-3 py-2.5 text-xs focus:outline-none focus:border-stone-400 text-stone-800"
            />
          </div>
          <button
            onClick={() => setShowFilters(!showFilters)}
            className={`flex items-center gap-1.5 px-3 py-2.5 border text-[10px] font-mono uppercase font-bold tracking-wider cursor-pointer transition-all ${
              showFilters || hasActiveFilters ? 'bg-stone-900 text-white border-stone-900' : 'bg-white border-stone-200 text-stone-600 hover:bg-stone-50'
            }`}
          >
            <Filter size={12} /> Filtros {hasActiveFilters ? `(${[priorityFilter, clientFilter, projectFilter, assigneeFilter].filter(v => v !== 'all').length + (searchQuery ? 1 : 0)})` : ''}
          </button>
          <button
            onClick={() => setShowArchived(!showArchived)}
            className={`flex items-center gap-1.5 px-3 py-2.5 border text-[10px] font-mono uppercase font-bold tracking-wider cursor-pointer transition-all ${
              showArchived ? 'bg-stone-900 text-white border-stone-900' : 'bg-white border-stone-200 text-stone-600 hover:bg-stone-50'
            }`}
            title="Mostrar/ocultar demandas arquivadas"
          >
            <Archive size={12} /> Arquivadas
          </button>
        </div>

        <AnimatePresence>
          {showFilters && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="overflow-hidden"
            >
              <div className="grid grid-cols-2 md:grid-cols-4 gap-2 bg-stone-50 border border-stone-200 p-3">
                <select
                  value={priorityFilter}
                  onChange={(e) => setPriorityFilter(e.target.value as any)}
                  className="bg-white border border-stone-200 p-2 text-[10px] font-mono uppercase text-stone-700 cursor-pointer"
                >
                  <option value="all">Toda Prioridade</option>
                  {Object.entries(PRIORITY_CONFIG).map(([k, v]) => (
                    <option key={k} value={k}>{v.label}</option>
                  ))}
                </select>
                <select
                  value={clientFilter}
                  onChange={(e) => { setClientFilter(e.target.value); setProjectFilter('all'); }}
                  className="bg-white border border-stone-200 p-2 text-[10px] font-mono uppercase text-stone-700 cursor-pointer"
                >
                  <option value="all">Todo Cliente</option>
                  {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                </select>
                <select
                  value={projectFilter}
                  onChange={(e) => setProjectFilter(e.target.value)}
                  className="bg-white border border-stone-200 p-2 text-[10px] font-mono uppercase text-stone-700 cursor-pointer"
                >
                  <option value="all">Toda Obra/Projeto</option>
                  {(clientFilter === 'all' ? projects : projectsForClient(clientFilter)).map(p => (
                    <option key={p.id} value={p.id}>{p.name}</option>
                  ))}
                </select>
                <select
                  value={assigneeFilter}
                  onChange={(e) => setAssigneeFilter(e.target.value)}
                  className="bg-white border border-stone-200 p-2 text-[10px] font-mono uppercase text-stone-700 cursor-pointer"
                >
                  <option value="all">Todo Responsável</option>
                  {teamMembers.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}
                </select>
              </div>
              {hasActiveFilters && (
                <button
                  onClick={clearFilters}
                  className="mt-1.5 text-[9px] font-mono uppercase text-stone-400 hover:text-stone-700 underline cursor-pointer"
                >
                  Limpar filtros
                </button>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* KANBAN BOARD */}
      <div className="grid grid-cols-1 md:grid-cols-3 xl:grid-cols-6 gap-3">
        {STATUS_COLUMNS.map((col, colIdx) => {
          const colDemands = filteredDemands.filter(d => d.status === col.id);
          return (
            <div
              key={col.id}
              onDragOver={(e) => { e.preventDefault(); setDragOverColumn(col.id); }}
              onDragLeave={() => setDragOverColumn(prev => (prev === col.id ? null : prev))}
              onDrop={(e) => { e.preventDefault(); handleDropOnColumn(col.id); }}
              className={`border border-stone-200 border-t-4 p-3 space-y-3 flex flex-col min-h-[420px] transition-colors ${col.headerColor} ${
                dragOverColumn === col.id ? 'ring-2 ring-[#FF5A35]/50' : ''
              }`}
            >
              {/* Column header */}
              <div className="flex items-center justify-between border-b border-stone-200/60 pb-2">
                <span className="font-mono text-[10px] font-bold uppercase tracking-wider text-stone-700">
                  {col.label}
                </span>
                <span className="text-[10px] font-mono bg-stone-200 text-stone-600 font-bold px-1.5 py-0.5 rounded-full">
                  {colDemands.length}
                </span>
              </div>

              {/* Quick add */}
              {quickAddColumn === col.id ? (
                <div className="space-y-1.5">
                  <input
                    autoFocus
                    type="text"
                    value={quickAddText}
                    onChange={(e) => setQuickAddText(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') { e.preventDefault(); handleQuickAdd(col.id); }
                      if (e.key === 'Escape') { setQuickAddColumn(null); setQuickAddText(''); }
                    }}
                    placeholder="Título da demanda..."
                    className="w-full bg-white border border-stone-300 p-2 text-[11px] focus:outline-none focus:border-stone-500"
                  />
                  <div className="flex gap-1.5">
                    <button
                      onClick={() => handleQuickAdd(col.id)}
                      className="flex-grow bg-stone-900 text-white text-[9px] font-mono uppercase font-bold py-1.5 cursor-pointer hover:bg-stone-800"
                    >
                      Adicionar
                    </button>
                    <button
                      onClick={() => { setQuickAddColumn(null); setQuickAddText(''); }}
                      className="px-2 border border-stone-300 text-stone-500 hover:bg-stone-100 cursor-pointer"
                    >
                      <X size={12} />
                    </button>
                  </div>
                </div>
              ) : (
                <button
                  onClick={() => { setQuickAddColumn(col.id); setQuickAddText(''); }}
                  className="flex items-center gap-1 text-[9px] font-mono uppercase font-bold text-stone-400 hover:text-stone-700 cursor-pointer"
                >
                  <Plus size={11} /> Adicionar cartão
                </button>
              )}

              {/* Cards */}
              <div className="space-y-2.5 flex-grow overflow-y-auto max-h-[560px] pr-0.5">
                {colDemands.length === 0 ? (
                  <div className="text-center py-8 border-2 border-dashed border-stone-200/60 text-stone-400 text-[9px] font-mono italic">
                    Sem demandas
                  </div>
                ) : (
                  colDemands.map(d => {
                    const pr = PRIORITY_CONFIG[d.priority];
                    const overdue = isOverdue(d);
                    const checklistTotal = d.checklist.length;
                    const checklistDone = d.checklist.filter(i => i.done).length;
                    const clientName = getClientName(d.clientId);
                    const projectName = getProjectName(d.projectId);
                    const assigneeName = getUserName(d.assigneeUserId);

                    return (
                      <div
                        key={d.id}
                        draggable
                        onDragStart={() => setDraggingId(d.id)}
                        onDragEnd={() => { setDraggingId(null); setDragOverColumn(null); }}
                        onClick={() => setDetailDemand(d)}
                        className={`bg-white border border-stone-200 border-l-4 ${pr.border} p-3 space-y-2 shadow-xs hover:shadow-sm transition-shadow cursor-pointer group ${
                          draggingId === d.id ? 'opacity-40' : ''
                        }`}
                      >
                        <div className="flex items-start justify-between gap-2">
                          <h5 className="font-sans text-[11px] font-bold text-stone-900 leading-snug flex-grow">
                            {d.title}
                          </h5>
                          {d.autoGenerated ? (
                            <span title="Gerada automaticamente pelo sistema" className="shrink-0">
                              <Zap size={12} className="text-purple-400" />
                            </span>
                          ) : (
                            <GripVertical size={12} className="text-stone-300 shrink-0 opacity-0 group-hover:opacity-100 transition-opacity" />
                          )}
                        </div>

                        {d.description && (
                          <p className="text-[9.5px] text-stone-500 leading-normal line-clamp-2">{d.description}</p>
                        )}

                        {(clientName || projectName) && (
                          <div className="flex flex-wrap gap-1">
                            {clientName && (
                              <span className="inline-flex items-center gap-1 px-1.5 py-0.5 bg-stone-50 border border-stone-150 text-[8px] font-mono text-stone-600">
                                <Building size={9} /> {clientName}
                              </span>
                            )}
                            {projectName && (
                              <span className="inline-flex items-center gap-1 px-1.5 py-0.5 bg-stone-50 border border-stone-150 text-[8px] font-mono text-stone-600">
                                <Briefcase size={9} /> {projectName}
                              </span>
                            )}
                          </div>
                        )}

                        {d.labels.length > 0 && (
                          <div className="flex flex-wrap gap-1">
                            {d.labels.map((l, i) => (
                              <span key={i} className="px-1.5 py-0.5 bg-[#FF5A35]/10 text-[#FF5A35] text-[8px] font-mono font-bold uppercase">
                                {l}
                              </span>
                            ))}
                          </div>
                        )}

                        <div className="flex items-center justify-between text-[8.5px] font-mono">
                          <span className={`px-1.5 py-0.5 border font-bold uppercase flex items-center gap-1 ${pr.badge}`}>
                            <Flag size={9} /> {pr.label}
                          </span>
                          {d.dueDate && (
                            <span className={`flex items-center gap-1 font-bold ${overdue ? 'text-red-600' : 'text-stone-400'}`}>
                              {overdue ? <AlertTriangle size={9} /> : <Calendar size={9} />}
                              {formatDate(d.dueDate)}
                            </span>
                          )}
                        </div>

                        <div className="flex items-center justify-between pt-1.5 mt-1 border-t border-stone-100">
                          <div className="flex items-center gap-2.5 text-[8.5px] text-stone-400 font-mono">
                            {checklistTotal > 0 && (
                              <span className="flex items-center gap-1">
                                <CheckSquare size={10} /> {checklistDone}/{checklistTotal}
                              </span>
                            )}
                            {d.comments.length > 0 && (
                              <span className="flex items-center gap-1">
                                <MessageSquare size={10} /> {d.comments.length}
                              </span>
                            )}
                            {assigneeName && (
                              <span className="flex items-center gap-1 truncate max-w-[70px]" title={assigneeName}>
                                <UserIcon size={10} /> {assigneeName}
                              </span>
                            )}
                          </div>

                          <div className="flex items-center gap-0.5" onClick={(e) => e.stopPropagation()}>
                            <button
                              onClick={() => handleMoveStatus(d, 'left')}
                              disabled={colIdx === 0}
                              className="p-1 hover:bg-stone-100 disabled:opacity-20 disabled:pointer-events-none text-stone-400"
                              title="Mover para trás"
                            >
                              <ChevronLeft size={11} />
                            </button>
                            <button
                              onClick={() => handleMoveStatus(d, 'right')}
                              disabled={colIdx === STATUS_COLUMNS.length - 1}
                              className="p-1 hover:bg-stone-100 disabled:opacity-20 disabled:pointer-events-none text-stone-400"
                              title="Mover para frente"
                            >
                              <ChevronRight size={11} />
                            </button>
                          </div>
                        </div>
                      </div>
                    );
                  })
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* ====================================================== */}
      {/* MODAL: CRIAR/EDITAR DEMANDA                             */}
      {/* ====================================================== */}
      {isModalOpen && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-xs p-4">
          <div className="bg-white border border-stone-200 max-w-lg w-full p-6 space-y-4 shadow-xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-stone-100 pb-3">
              <h3 className="font-serif text-lg text-stone-900 font-bold">
                {editingDemand ? 'Editar Demanda' : 'Nova Demanda'}
              </h3>
              <button onClick={() => setIsModalOpen(false)} className="text-stone-400 hover:text-stone-600 cursor-pointer">
                <X size={18} />
              </button>
            </div>

            <form onSubmit={handleSaveDemand} className="space-y-4 text-xs">
              {templates.length > 0 && (
                <div className="flex gap-1.5 bg-stone-50 border border-stone-200 p-2.5">
                  <select
                    value={applyTemplateId}
                    onChange={(e) => setApplyTemplateId(e.target.value)}
                    className="flex-grow bg-white border border-stone-200 p-2 text-[10px] font-mono uppercase text-stone-700 cursor-pointer"
                  >
                    <option value="">Aplicar modelo...</option>
                    {templates.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}
                  </select>
                  <button
                    type="button"
                    disabled={!applyTemplateId}
                    onClick={handleApplyTemplateToForm}
                    className="px-3 bg-stone-800 hover:bg-stone-900 disabled:opacity-30 disabled:pointer-events-none text-white text-[9px] font-mono uppercase font-bold cursor-pointer flex items-center gap-1"
                  >
                    <Sparkles size={11} /> Aplicar
                  </button>
                </div>
              )}

              <div className="space-y-1">
                <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Título</label>
                <input
                  type="text"
                  required
                  autoFocus
                  value={form.title}
                  onChange={(e) => setForm({ ...form, title: e.target.value })}
                  className="w-full bg-stone-50 border border-stone-200 p-2.5 focus:outline-none focus:border-stone-400 text-stone-800"
                  placeholder="Ex: Enviar proposta comercial para cliente X"
                />
              </div>

              <div className="space-y-1">
                <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Descrição</label>
                <textarea
                  value={form.description}
                  onChange={(e) => setForm({ ...form, description: e.target.value })}
                  className="w-full bg-stone-50 border border-stone-200 p-2.5 focus:outline-none focus:border-stone-400 text-stone-800 min-h-[80px]"
                  placeholder="Detalhes da demanda..."
                />
              </div>

              {!editingDemand && formChecklist.length > 0 && (
                <div className="space-y-1.5">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold flex items-center gap-1">
                    <CheckSquare size={11} /> Checklist Inicial
                  </label>
                  <div className="space-y-1">
                    {formChecklist.map((text, i) => (
                      <div key={i} className="flex items-center gap-2 bg-stone-50 border border-stone-100 px-2 py-1.5">
                        <span className="text-[10px] text-stone-700 flex-grow">{text}</span>
                        <button
                          type="button"
                          onClick={() => setFormChecklist(prev => prev.filter((_, idx) => idx !== i))}
                          className="text-stone-300 hover:text-red-500 cursor-pointer"
                        >
                          <X size={11} />
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Status</label>
                  <select
                    value={form.status}
                    onChange={(e) => setForm({ ...form, status: e.target.value as DemandStatus })}
                    className="w-full bg-stone-50 border border-stone-200 p-2.5 focus:outline-none focus:border-stone-400 text-stone-800 cursor-pointer"
                  >
                    {STATUS_COLUMNS.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Prioridade</label>
                  <select
                    value={form.priority}
                    onChange={(e) => setForm({ ...form, priority: e.target.value as DemandPriority })}
                    className="w-full bg-stone-50 border border-stone-200 p-2.5 focus:outline-none focus:border-stone-400 text-stone-800 cursor-pointer"
                  >
                    {Object.entries(PRIORITY_CONFIG).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold flex items-center gap-1">
                    <Building size={11} /> Cliente
                  </label>
                  <select
                    value={form.clientId}
                    onChange={(e) => setForm({ ...form, clientId: e.target.value, projectId: '' })}
                    className="w-full bg-stone-50 border border-stone-200 p-2.5 focus:outline-none focus:border-stone-400 text-stone-800 cursor-pointer"
                  >
                    <option value="">Nenhum</option>
                    {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold flex items-center gap-1">
                    <Briefcase size={11} /> Obra/Projeto
                  </label>
                  <select
                    value={form.projectId}
                    onChange={(e) => setForm({ ...form, projectId: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2.5 focus:outline-none focus:border-stone-400 text-stone-800 cursor-pointer"
                  >
                    <option value="">Nenhum</option>
                    {(form.clientId ? projectsForClient(form.clientId) : projects).map(p => (
                      <option key={p.id} value={p.id}>{p.name}</option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold flex items-center gap-1">
                    <UserIcon size={11} /> Responsável
                  </label>
                  <select
                    value={form.assigneeUserId}
                    onChange={(e) => setForm({ ...form, assigneeUserId: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2.5 focus:outline-none focus:border-stone-400 text-stone-800 cursor-pointer"
                  >
                    <option value="">Sem responsável</option>
                    {teamMembers.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold flex items-center gap-1">
                    <Calendar size={11} /> Prazo
                  </label>
                  <input
                    type="date"
                    value={form.dueDate}
                    onChange={(e) => setForm({ ...form, dueDate: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2.5 focus:outline-none focus:border-stone-400 text-stone-800"
                  />
                </div>
              </div>

              <div className="space-y-1">
                <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold flex items-center gap-1">
                  <TagIcon size={11} /> Etiquetas (separadas por vírgula)
                </label>
                <input
                  type="text"
                  value={form.labels}
                  onChange={(e) => setForm({ ...form, labels: e.target.value })}
                  className="w-full bg-stone-50 border border-stone-200 p-2.5 focus:outline-none focus:border-stone-400 text-stone-800"
                  placeholder="Ex: financeiro, urgente, cliente vip"
                />
              </div>

              <div className="flex gap-3 pt-2">
                <button
                  type="submit"
                  className="flex-grow bg-stone-900 hover:bg-stone-800 text-white font-mono text-[10px] uppercase tracking-wider font-bold py-3 cursor-pointer"
                >
                  {editingDemand ? 'Salvar Alterações' : 'Criar Demanda'}
                </button>
                {editingDemand && (
                  <button
                    type="button"
                    onClick={() => { setIsModalOpen(false); handleDeleteDemand(editingDemand.id); }}
                    className="px-4 border border-red-200 text-red-600 hover:bg-red-50 font-mono text-[10px] uppercase tracking-wider font-bold cursor-pointer"
                  >
                    <Trash2 size={13} />
                  </button>
                )}
              </div>
            </form>
          </div>
        </div>
      )}

      {/* ====================================================== */}
      {/* MODAL: DETALHE DA DEMANDA (checklist + comentários)     */}
      {/* ====================================================== */}
      {detailDemand && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-xs p-4">
          <div className="bg-white border border-stone-200 max-w-xl w-full p-6 space-y-5 shadow-xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-start justify-between border-b border-stone-100 pb-3 gap-3">
              <div className="space-y-1">
                <div className="flex items-center gap-2 flex-wrap">
                  <span className={`px-1.5 py-0.5 border text-[8px] font-mono font-bold uppercase ${PRIORITY_CONFIG[detailDemand.priority].badge}`}>
                    {PRIORITY_CONFIG[detailDemand.priority].label}
                  </span>
                  <span className="text-[8px] font-mono uppercase text-stone-400">
                    {STATUS_COLUMNS.find(c => c.id === detailDemand.status)?.label}
                  </span>
                  {detailDemand.autoGenerated && (
                    <span className="text-[8px] font-mono uppercase text-purple-500 flex items-center gap-1"><Zap size={9} /> Automática</span>
                  )}
                  {detailDemand.archived && (
                    <span className="text-[8px] font-mono uppercase text-stone-400 flex items-center gap-1"><Archive size={9} /> Arquivada</span>
                  )}
                </div>
                <h3 className="font-serif text-lg text-stone-900 font-bold">{detailDemand.title}</h3>
              </div>
              <div className="flex items-center gap-1 shrink-0">
                <button
                  onClick={() => handleOpenEdit(detailDemand)}
                  className="p-1.5 text-stone-500 hover:text-stone-900 hover:bg-stone-100 border border-stone-100 cursor-pointer"
                  title="Editar"
                >
                  <Edit size={14} />
                </button>
                <button
                  onClick={() => handleArchive(detailDemand, !detailDemand.archived)}
                  className="p-1.5 text-stone-500 hover:text-stone-900 hover:bg-stone-100 border border-stone-100 cursor-pointer"
                  title={detailDemand.archived ? 'Desarquivar' : 'Arquivar'}
                >
                  <Archive size={14} />
                </button>
                <button
                  onClick={() => setDetailDemand(null)}
                  className="p-1.5 text-stone-400 hover:text-stone-600 cursor-pointer"
                >
                  <X size={16} />
                </button>
              </div>
            </div>

            {detailDemand.description && (
              <p className="text-xs text-stone-600 leading-relaxed">{detailDemand.description}</p>
            )}

            <div className="flex flex-wrap gap-2 text-[9px] font-mono">
              {getClientName(detailDemand.clientId) && (
                <span className="inline-flex items-center gap-1 px-2 py-1 bg-stone-50 border border-stone-150 text-stone-600">
                  <Building size={10} /> {getClientName(detailDemand.clientId)}
                </span>
              )}
              {getProjectName(detailDemand.projectId) && (
                <span className="inline-flex items-center gap-1 px-2 py-1 bg-stone-50 border border-stone-150 text-stone-600">
                  <Briefcase size={10} /> {getProjectName(detailDemand.projectId)}
                </span>
              )}
              {getUserName(detailDemand.assigneeUserId) && (
                <span className="inline-flex items-center gap-1 px-2 py-1 bg-stone-50 border border-stone-150 text-stone-600">
                  <UserIcon size={10} /> {getUserName(detailDemand.assigneeUserId)}
                </span>
              )}
              {detailDemand.dueDate && (
                <span className={`inline-flex items-center gap-1 px-2 py-1 border ${isOverdue(detailDemand) ? 'bg-red-50 border-red-100 text-red-600' : 'bg-stone-50 border-stone-150 text-stone-600'}`}>
                  <Calendar size={10} /> {formatDate(detailDemand.dueDate)}
                </span>
              )}
              {detailDemand.labels.map((l, i) => (
                <span key={i} className="px-2 py-1 bg-[#FF5A35]/10 text-[#FF5A35] font-bold uppercase">{l}</span>
              ))}
            </div>

            {/* Checklist */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold flex items-center gap-1">
                  <CheckSquare size={11} /> Checklist
                </label>
                {detailDemand.checklist.length > 0 && (
                  <span className="text-[9px] font-mono text-stone-400">
                    {detailDemand.checklist.filter(i => i.done).length}/{detailDemand.checklist.length}
                  </span>
                )}
              </div>

              {detailDemand.checklist.length > 0 && (
                <div className="w-full h-1.5 bg-stone-100">
                  <div
                    className="h-1.5 bg-emerald-400 transition-all"
                    style={{
                      width: `${detailDemand.checklist.length ? (detailDemand.checklist.filter(i => i.done).length / detailDemand.checklist.length) * 100 : 0}%`,
                    }}
                  />
                </div>
              )}

              <div className="space-y-1">
                {detailDemand.checklist.map(item => (
                  <div key={item.id} className="flex items-center gap-2 group">
                    <button onClick={() => handleToggleChecklistItem(item.id)} className="text-stone-500 hover:text-emerald-600 cursor-pointer">
                      {item.done ? <CheckSquare size={14} className="text-emerald-500" /> : <Square size={14} />}
                    </button>
                    <span className={`text-xs flex-grow ${item.done ? 'line-through text-stone-400' : 'text-stone-700'}`}>{item.text}</span>
                    <button
                      onClick={() => handleRemoveChecklistItem(item.id)}
                      className="opacity-0 group-hover:opacity-100 text-stone-300 hover:text-red-500 cursor-pointer transition-opacity"
                    >
                      <X size={12} />
                    </button>
                  </div>
                ))}
              </div>

              <div className="flex gap-1.5">
                <input
                  type="text"
                  value={newChecklistText}
                  onChange={(e) => setNewChecklistText(e.target.value)}
                  onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); handleAddChecklistItem(); } }}
                  placeholder="Adicionar item..."
                  className="flex-grow bg-stone-50 border border-stone-200 p-2 text-xs focus:outline-none focus:border-stone-400"
                />
                <button
                  onClick={handleAddChecklistItem}
                  className="px-3 bg-stone-100 hover:bg-stone-200 border border-stone-200 text-stone-600 cursor-pointer"
                >
                  <Plus size={13} />
                </button>
              </div>

              {templates.length > 0 && (
                <select
                  value=""
                  onChange={(e) => { if (e.target.value) handleApplyTemplateToDetail(e.target.value); }}
                  className="w-full bg-stone-50 border border-stone-200 p-2 text-[9px] font-mono uppercase text-stone-500 cursor-pointer"
                >
                  <option value="">+ Adicionar itens de um modelo...</option>
                  {templates.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}
                </select>
              )}
            </div>

            {/* Comments */}
            <div className="space-y-2 pt-2 border-t border-stone-100">
              <label className="text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold flex items-center gap-1">
                <MessageSquare size={11} /> Comentários
              </label>

              <div className="space-y-2 max-h-[180px] overflow-y-auto">
                {detailDemand.comments.length === 0 ? (
                  <p className="text-[10px] text-stone-400 italic">Nenhum comentário ainda.</p>
                ) : (
                  detailDemand.comments.map(c => (
                    <div key={c.id} className="bg-stone-50 border border-stone-100 p-2.5 space-y-0.5">
                      <div className="flex items-center justify-between">
                        <span className="text-[9px] font-mono font-bold text-stone-700">{c.author}</span>
                        <span className="text-[8px] font-mono text-stone-400">
                          {new Date(c.createdAt).toLocaleString('pt-BR', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' })}
                        </span>
                      </div>
                      <p className="text-xs text-stone-700">{c.text}</p>
                    </div>
                  ))
                )}
              </div>

              <div className="space-y-1.5">
                <input
                  type="text"
                  value={commentAuthor}
                  onChange={(e) => setCommentAuthor(e.target.value)}
                  placeholder="Seu nome"
                  className="w-full bg-stone-50 border border-stone-200 p-2 text-[10px] focus:outline-none focus:border-stone-400"
                />
                <div className="flex gap-1.5">
                  <textarea
                    value={newCommentText}
                    onChange={(e) => setNewCommentText(e.target.value)}
                    placeholder="Escreva um comentário..."
                    className="flex-grow bg-stone-50 border border-stone-200 p-2 text-xs focus:outline-none focus:border-stone-400 min-h-[44px]"
                  />
                  <button
                    onClick={handleAddComment}
                    className="px-3 bg-stone-900 hover:bg-stone-800 text-white cursor-pointer flex items-center justify-center"
                    title="Enviar comentário"
                  >
                    <Send size={14} />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ====================================================== */}
      {/* MODAL: MODELOS DE DEMANDA                               */}
      {/* ====================================================== */}
      {isTemplatesOpen && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-xs p-4">
          <div className="bg-white border border-stone-200 max-w-2xl w-full p-6 space-y-5 shadow-xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-stone-100 pb-3">
              <h3 className="font-serif text-lg text-stone-900 font-bold flex items-center gap-2">
                <Layers size={16} className="text-[#FF5A35]" /> Modelos de Demanda
              </h3>
              <button onClick={() => setIsTemplatesOpen(false)} className="text-stone-400 hover:text-stone-600 cursor-pointer">
                <X size={18} />
              </button>
            </div>

            <div className="grid md:grid-cols-2 gap-5">
              {/* Lista */}
              <div className="space-y-2">
                <p className="text-[9px] font-mono uppercase tracking-wider text-stone-400 font-bold">Modelos cadastrados</p>
                {templates.length === 0 ? (
                  <p className="text-[10px] text-stone-400 italic">Nenhum modelo ainda. Crie o primeiro ao lado.</p>
                ) : (
                  <div className="space-y-2 max-h-[420px] overflow-y-auto pr-1">
                    {templates.map(t => (
                      <div key={t.id} className="border border-stone-200 p-3 space-y-1.5">
                        <div className="flex items-center justify-between">
                          <span className="text-xs font-bold text-stone-900">{t.name}</span>
                          <div className="flex gap-1">
                            <button onClick={() => handleEditTemplateClick(t)} className="p-1 text-stone-400 hover:text-stone-800 cursor-pointer"><Edit size={12} /></button>
                            <button onClick={() => handleDeleteTemplate(t.id)} className="p-1 text-stone-400 hover:text-red-600 cursor-pointer"><Trash2 size={12} /></button>
                          </div>
                        </div>
                        {t.description && <p className="text-[10px] text-stone-500">{t.description}</p>}
                        <div className="flex flex-wrap gap-1">
                          <span className={`px-1.5 py-0.5 text-[8px] font-mono font-bold uppercase border ${PRIORITY_CONFIG[t.defaultPriority].badge}`}>{PRIORITY_CONFIG[t.defaultPriority].label}</span>
                          {t.isDefaultForNewClient && <span className="px-1.5 py-0.5 text-[8px] font-mono font-bold uppercase bg-emerald-50 text-emerald-700 border border-emerald-100">Padrão · Cliente Novo</span>}
                          {t.isDefaultForNewProject && <span className="px-1.5 py-0.5 text-[8px] font-mono font-bold uppercase bg-blue-50 text-blue-700 border border-blue-100">Padrão · Obra Nova</span>}
                        </div>
                        {t.checklist.length > 0 && (
                          <p className="text-[9px] text-stone-400 font-mono">{t.checklist.length} item(ns) de checklist</p>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Formulário */}
              <form onSubmit={handleSaveTemplate} className="space-y-3 text-xs border-l border-stone-100 pl-5">
                <p className="text-[9px] font-mono uppercase tracking-wider text-stone-400 font-bold">
                  {editingTemplate ? 'Editar modelo' : 'Novo modelo'}
                </p>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Nome</label>
                  <input
                    type="text"
                    required
                    value={templateForm.name}
                    onChange={(e) => setTemplateForm({ ...templateForm, name: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2 focus:outline-none focus:border-stone-400"
                    placeholder="Ex: Onboarding de Cliente"
                  />
                </div>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Descrição</label>
                  <textarea
                    value={templateForm.description}
                    onChange={(e) => setTemplateForm({ ...templateForm, description: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2 focus:outline-none focus:border-stone-400 min-h-[50px]"
                  />
                </div>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Prioridade Padrão</label>
                  <select
                    value={templateForm.defaultPriority}
                    onChange={(e) => setTemplateForm({ ...templateForm, defaultPriority: e.target.value as DemandPriority })}
                    className="w-full bg-stone-50 border border-stone-200 p-2 cursor-pointer"
                  >
                    {Object.entries(PRIORITY_CONFIG).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Etiquetas Padrão (vírgula)</label>
                  <input
                    type="text"
                    value={templateForm.defaultLabels}
                    onChange={(e) => setTemplateForm({ ...templateForm, defaultLabels: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2 focus:outline-none focus:border-stone-400"
                  />
                </div>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Checklist (um item por linha)</label>
                  <textarea
                    value={templateForm.checklist}
                    onChange={(e) => setTemplateForm({ ...templateForm, checklist: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2 focus:outline-none focus:border-stone-400 min-h-[90px] font-mono text-[11px]"
                    placeholder={'Enviar contrato para assinatura\nCadastrar acesso do cliente\nAgendar reunião de kickoff'}
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="flex items-center gap-2 text-[10px] text-stone-600 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={templateForm.isDefaultForNewClient}
                      onChange={(e) => setTemplateForm({ ...templateForm, isDefaultForNewClient: e.target.checked })}
                    />
                    Usar como padrão sempre que um cliente novo for cadastrado
                  </label>
                  <label className="flex items-center gap-2 text-[10px] text-stone-600 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={templateForm.isDefaultForNewProject}
                      onChange={(e) => setTemplateForm({ ...templateForm, isDefaultForNewProject: e.target.checked })}
                    />
                    Usar como padrão sempre que uma obra/projeto novo for cadastrado
                  </label>
                </div>
                <div className="flex gap-2 pt-1">
                  <button type="submit" className="flex-grow bg-stone-900 hover:bg-stone-800 text-white font-mono text-[10px] uppercase font-bold py-2.5 cursor-pointer">
                    {editingTemplate ? 'Salvar Modelo' : 'Criar Modelo'}
                  </button>
                  {editingTemplate && (
                    <button
                      type="button"
                      onClick={() => { setEditingTemplate(null); setTemplateForm(emptyTemplateForm()); }}
                      className="px-3 border border-stone-200 text-stone-500 hover:bg-stone-50 cursor-pointer"
                    >
                      <X size={13} />
                    </button>
                  )}
                </div>
              </form>
            </div>
          </div>
        </div>
      )}

      {/* ====================================================== */}
      {/* MODAL: RECORRÊNCIAS                                     */}
      {/* ====================================================== */}
      {isRecurrenceOpen && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-xs p-4">
          <div className="bg-white border border-stone-200 max-w-2xl w-full p-6 space-y-5 shadow-xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-stone-100 pb-3">
              <h3 className="font-serif text-lg text-stone-900 font-bold flex items-center gap-2">
                <Repeat size={16} className="text-[#FF5A35]" /> Demandas Recorrentes
              </h3>
              <button onClick={() => setIsRecurrenceOpen(false)} className="text-stone-400 hover:text-stone-600 cursor-pointer">
                <X size={18} />
              </button>
            </div>

            <div className="grid md:grid-cols-2 gap-5">
              {/* Lista */}
              <div className="space-y-2">
                <p className="text-[9px] font-mono uppercase tracking-wider text-stone-400 font-bold">Recorrências ativas</p>
                {recurringMasters.length === 0 ? (
                  <p className="text-[10px] text-stone-400 italic">Nenhuma recorrência cadastrada ainda.</p>
                ) : (
                  <div className="space-y-2 max-h-[420px] overflow-y-auto pr-1">
                    {recurringMasters.map(m => (
                      <div key={m.id} className="border border-stone-200 p-3 space-y-1.5">
                        <div className="flex items-center justify-between">
                          <span className="text-xs font-bold text-stone-900">{m.title}</span>
                          <div className="flex gap-1">
                            <button
                              onClick={() => handleToggleRecurrenceActive(m)}
                              className="p-1 text-stone-400 hover:text-stone-800 cursor-pointer"
                              title={m.recurrence?.active ? 'Pausar' : 'Retomar'}
                            >
                              {m.recurrence?.active ? <Pause size={12} /> : <Play size={12} />}
                            </button>
                            <button onClick={() => handleEditRecurrenceClick(m)} className="p-1 text-stone-400 hover:text-stone-800 cursor-pointer"><Edit size={12} /></button>
                            <button onClick={() => handleDeleteRecurrence(m.id)} className="p-1 text-stone-400 hover:text-red-600 cursor-pointer"><Trash2 size={12} /></button>
                          </div>
                        </div>
                        <div className="flex flex-wrap gap-1 items-center text-[9px] font-mono">
                          <span className={`px-1.5 py-0.5 font-bold uppercase border ${m.recurrence?.active ? 'bg-emerald-50 text-emerald-700 border-emerald-100' : 'bg-stone-100 text-stone-500 border-stone-200'}`}>
                            {m.recurrence?.active ? 'Ativa' : 'Pausada'}
                          </span>
                          <span className="text-stone-500">{RECURRENCE_LABELS[m.recurrence?.interval || 'semanal']}</span>
                          <span className="text-stone-400">· próxima: {formatDate(m.recurrence?.nextRunDate)}</span>
                        </div>
                        {(getClientName(m.clientId) || getProjectName(m.projectId)) && (
                          <div className="flex flex-wrap gap-1">
                            {getClientName(m.clientId) && <span className="px-1.5 py-0.5 bg-stone-50 border border-stone-150 text-[8px] font-mono text-stone-600">{getClientName(m.clientId)}</span>}
                            {getProjectName(m.projectId) && <span className="px-1.5 py-0.5 bg-stone-50 border border-stone-150 text-[8px] font-mono text-stone-600">{getProjectName(m.projectId)}</span>}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Formulário */}
              <form onSubmit={handleSaveRecurrence} className="space-y-3 text-xs border-l border-stone-100 pl-5">
                <p className="text-[9px] font-mono uppercase tracking-wider text-stone-400 font-bold">
                  {editingRecurrence ? 'Editar recorrência' : 'Nova recorrência'}
                </p>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Título</label>
                  <input
                    type="text"
                    required
                    value={recForm.title}
                    onChange={(e) => setRecForm({ ...recForm, title: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2 focus:outline-none focus:border-stone-400"
                    placeholder="Ex: Visita semanal à obra"
                  />
                </div>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Descrição</label>
                  <textarea
                    value={recForm.description}
                    onChange={(e) => setRecForm({ ...recForm, description: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2 focus:outline-none focus:border-stone-400 min-h-[50px]"
                  />
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <div className="space-y-1">
                    <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Frequência</label>
                    <select
                      value={recForm.interval}
                      onChange={(e) => setRecForm({ ...recForm, interval: e.target.value as RecurrenceInterval })}
                      className="w-full bg-stone-50 border border-stone-200 p-2 cursor-pointer"
                    >
                      {Object.entries(RECURRENCE_LABELS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
                    </select>
                  </div>
                  <div className="space-y-1">
                    <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Próxima Ocorrência</label>
                    <input
                      type="date"
                      value={recForm.startDate}
                      onChange={(e) => setRecForm({ ...recForm, startDate: e.target.value })}
                      className="w-full bg-stone-50 border border-stone-200 p-2"
                    />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <div className="space-y-1">
                    <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Prioridade</label>
                    <select
                      value={recForm.priority}
                      onChange={(e) => setRecForm({ ...recForm, priority: e.target.value as DemandPriority })}
                      className="w-full bg-stone-50 border border-stone-200 p-2 cursor-pointer"
                    >
                      {Object.entries(PRIORITY_CONFIG).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}
                    </select>
                  </div>
                  <div className="space-y-1">
                    <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Nasce na coluna</label>
                    <select
                      value={recForm.targetStatus}
                      onChange={(e) => setRecForm({ ...recForm, targetStatus: e.target.value as DemandStatus })}
                      className="w-full bg-stone-50 border border-stone-200 p-2 cursor-pointer"
                    >
                      {STATUS_COLUMNS.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}
                    </select>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <div className="space-y-1">
                    <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Cliente</label>
                    <select
                      value={recForm.clientId}
                      onChange={(e) => setRecForm({ ...recForm, clientId: e.target.value, projectId: '' })}
                      className="w-full bg-stone-50 border border-stone-200 p-2 cursor-pointer"
                    >
                      <option value="">Nenhum</option>
                      {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                    </select>
                  </div>
                  <div className="space-y-1">
                    <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Obra/Projeto</label>
                    <select
                      value={recForm.projectId}
                      onChange={(e) => setRecForm({ ...recForm, projectId: e.target.value })}
                      className="w-full bg-stone-50 border border-stone-200 p-2 cursor-pointer"
                    >
                      <option value="">Nenhum</option>
                      {(recForm.clientId ? projectsForClient(recForm.clientId) : projects).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                    </select>
                  </div>
                </div>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Responsável</label>
                  <select
                    value={recForm.assigneeUserId}
                    onChange={(e) => setRecForm({ ...recForm, assigneeUserId: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2 cursor-pointer"
                  >
                    <option value="">Sem responsável</option>
                    {teamMembers.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Etiquetas (vírgula)</label>
                  <input
                    type="text"
                    value={recForm.labels}
                    onChange={(e) => setRecForm({ ...recForm, labels: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2 focus:outline-none focus:border-stone-400"
                  />
                </div>
                <div className="space-y-1">
                  <label className="block text-[9px] font-mono uppercase tracking-wider text-stone-500 font-bold">Checklist (um item por linha)</label>
                  <textarea
                    value={recForm.checklist}
                    onChange={(e) => setRecForm({ ...recForm, checklist: e.target.value })}
                    className="w-full bg-stone-50 border border-stone-200 p-2 focus:outline-none focus:border-stone-400 min-h-[70px] font-mono text-[11px]"
                  />
                </div>
                <div className="flex gap-2 pt-1">
                  <button type="submit" className="flex-grow bg-stone-900 hover:bg-stone-800 text-white font-mono text-[10px] uppercase font-bold py-2.5 cursor-pointer">
                    {editingRecurrence ? 'Salvar Recorrência' : 'Criar Recorrência'}
                  </button>
                  {editingRecurrence && (
                    <button
                      type="button"
                      onClick={() => { setEditingRecurrence(null); setRecForm(emptyRecForm()); }}
                      className="px-3 border border-stone-200 text-stone-500 hover:bg-stone-50 cursor-pointer"
                    >
                      <X size={13} />
                    </button>
                  )}
                </div>
              </form>
            </div>
          </div>
        </div>
      )}

      {/* ====================================================== */}
      {/* MODAL: CONFIGURAÇÕES DE AUTOMAÇÃO                       */}
      {/* ====================================================== */}
      {isAutomationOpen && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-xs p-4">
          <div className="bg-white border border-stone-200 max-w-md w-full p-6 space-y-4 shadow-xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-stone-100 pb-3">
              <h3 className="font-serif text-lg text-stone-900 font-bold flex items-center gap-2">
                <Settings size={16} className="text-[#FF5A35]" /> Automação de Demandas
              </h3>
              <button onClick={() => setIsAutomationOpen(false)} className="text-stone-400 hover:text-stone-600 cursor-pointer">
                <X size={18} />
              </button>
            </div>
            <p className="text-[10px] text-stone-400 italic">
              O sistema verifica essas condições continuamente enquanto o admin está logado e cria (ou resolve) demandas sozinho.
            </p>

            <form onSubmit={handleSaveAutomation} className="space-y-4 text-xs">
              <div className="border border-stone-200 p-3 space-y-2">
                <label className="flex items-center justify-between cursor-pointer">
                  <span className="text-[10px] font-mono uppercase font-bold text-stone-700">Cotações paradas</span>
                  <input
                    type="checkbox"
                    checked={autoForm.quotationsEnabled}
                    onChange={(e) => setAutoForm({ ...autoForm, quotationsEnabled: e.target.checked })}
                  />
                </label>
                <div className="flex items-center gap-2">
                  <span className="text-[9px] text-stone-500">Alertar após</span>
                  <input
                    type="number"
                    min={1}
                    value={autoForm.quotationPendingDays}
                    onChange={(e) => setAutoForm({ ...autoForm, quotationPendingDays: Math.max(1, parseInt(e.target.value) || 1) })}
                    className="w-16 bg-stone-50 border border-stone-200 p-1.5 text-center"
                  />
                  <span className="text-[9px] text-stone-500">dias parada em "pendente"</span>
                </div>
              </div>

              <div className="border border-stone-200 p-3 space-y-2">
                <label className="flex items-center justify-between cursor-pointer">
                  <span className="text-[10px] font-mono uppercase font-bold text-stone-700">Fases de cronograma atrasadas</span>
                  <input
                    type="checkbox"
                    checked={autoForm.phasesEnabled}
                    onChange={(e) => setAutoForm({ ...autoForm, phasesEnabled: e.target.checked })}
                  />
                </label>
                <div className="flex items-center gap-2">
                  <span className="text-[9px] text-stone-500">Alertar após</span>
                  <input
                    type="number"
                    min={1}
                    value={autoForm.phaseDelayDays}
                    onChange={(e) => setAutoForm({ ...autoForm, phaseDelayDays: Math.max(1, parseInt(e.target.value) || 1) })}
                    className="w-16 bg-stone-50 border border-stone-200 p-1.5 text-center"
                  />
                  <span className="text-[9px] text-stone-500">dias de atraso na fase</span>
                </div>
              </div>

              <div className="border border-stone-200 p-3 space-y-2">
                <label className="flex items-center justify-between cursor-pointer">
                  <span className="text-[10px] font-mono uppercase font-bold text-stone-700">Financeiro pendente vencido</span>
                  <input
                    type="checkbox"
                    checked={autoForm.transactionsEnabled}
                    onChange={(e) => setAutoForm({ ...autoForm, transactionsEnabled: e.target.checked })}
                  />
                </label>
                <div className="flex items-center gap-2">
                  <span className="text-[9px] text-stone-500">Alertar após</span>
                  <input
                    type="number"
                    min={1}
                    value={autoForm.transactionOverdueDays}
                    onChange={(e) => setAutoForm({ ...autoForm, transactionOverdueDays: Math.max(1, parseInt(e.target.value) || 1) })}
                    className="w-16 bg-stone-50 border border-stone-200 p-1.5 text-center"
                  />
                  <span className="text-[9px] text-stone-500">dias vencida em "pendente"</span>
                </div>
              </div>

              <button type="submit" className="w-full bg-stone-900 hover:bg-stone-800 text-white font-mono text-[10px] uppercase tracking-wider font-bold py-3 cursor-pointer">
                Salvar Configurações
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
